### ISSUE TITLE
Changing order of folders

### ISSUE THREAD

**Issue by stefanopagliari** [data-engineering-community/data-engineering-wiki#12]
@JPHaus. Thank you for sharing the 'publish.js' file that you are using to change the order in which files appear in the navigation bar.
Do you know if/how it is possible to change the publish.js file to also change the order of folders in the navigation bar rather than simply of notes?

**Comment by JPHaus** [comment]
Hi @stefanopagliari, I'm quite a beginner when it comes to JS and I believe I got the code from the [Obsidian forum](https://forum.obsidian.md/). I'd say ask there because I'm sure someone has done it before.

**Comment by stefanopagliari** [comment]
Thank you
