### ISSUE TITLE
Creating a SQL "bible" of sorts

### ISSUE THREAD

**Issue by digitalghost-dev** [data-engineering-community/data-engineering-wiki#14]
I've been learning SQL over the past 1/2 year and the concepts aren't sticking to me like they are with Python. I've been making a dictionary of SQL concepts/tools but I realized that the wiki could benefit from one. Here is an example from [my Notion page](https://curse-cairnsmore-977.notion.site/SQL-d87c6c26389243ca976338ef767f3a7e). 

What do you think about building a section/page for SQL related concepts? I know there is the [SQL page](https://dataengineering.wiki/Tools/SQL) already but maybe a quick reference guide like this could be useful since SQL is a huge part of the data world.

**Comment by JPHaus** [comment]
Yeah we can definitely expand the SQL section. Do you mind if we take inspiration from your notion site at all? Probably won't be able to get to it this week but I can get it started.

**Comment by digitalghost-dev** [comment]
@JPHaus Yes, taking inspiration from there is fine. I'd like to contribute to it as well if you're fine with that. Not sure if you want to lay out the structure of it first though?

**Comment by JPHaus** [comment]
Yes your contribution would be great! I'll get it started this week and we can collaborate on it.

**Comment by JPHaus** [comment]
@digitalghost-dev I started a SQL guide with a high-level structure and added some ideas already but it's still mostly placeholders ([sql-guide branch](https://github.com/data-engineering-community/data-engineering-wiki/tree/sql-guide)). Open to suggestions for different formats if you believe something else would make more sense. Otherwise, I'll be adding to it when I get time this/next week.

**Comment by digitalghost-dev** [comment]
@JPHaus cool, do you have a Discord or some other sort of communication? Still a bit of a beginner with branches and stuff and don't want to mess something up.

**Comment by JPHaus** [comment]
I'd prefer to keep communication all in one place but you won't have to worry about messing anything up with GitHub. Here's a good tutorial to get started: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by digitalghost-dev** [comment]
@JPHaus Okay. 

* I like your initial setup with the different skill levels. I think that is a good way to organize it. My only concern is categorizing which concepts are beginner, intermediate, or advanced. If we leave it up to your interpretation then it'll be fine but having a lot of different inputs on where a concept should go could be an issue.

* Should it be called it "SQL Guide" or "SQL Dictionary"? I liked the idea of it being more of a reference book than it being a guide and teaching you things.

* Did you want examples under each concept?

**Comment by JPHaus** [comment]
I see what you're saying. Instead of the guide, we can just add the concepts and then add them to the existing SQL note / organize them after.

**Comment by digitalghost-dev** [comment]
@JPHaus - I added some more information. What do you think of the structure? I was also going to add some images like I have in Notion and links to web references.

**Comment by JPHaus** [comment]
Content looks good and I wouldn't worry too much about the structure right now. Feel free to add images. You can store them under /assets and resize them like `![[Assets/my-image.png|200]]`

**Comment by JPHaus** [comment]
@digitalghost-dev I think we're ready to publish this! Do you have any thoughts or concerns about publishing? See PR: https://github.com/data-engineering-community/data-engineering-wiki/pull/27

**Comment by digitalghost-dev** [comment]
@JPHaus - Looks great, one thing I noticed is that the reference to correlated subqueries is bringing in the "this note in GitHub" for that page then right after, it shows the "this note in GitHub" for the SQL Guide. Not sure if you like the way this looks or want to just copy and paste the contact from correlated subqueries over so that part doesn't show. Other than that, this looks good for a V1.

**Comment by JPHaus** [comment]
Yeah the goal would be to remove that with some js or add an H1 to each note and filter by that. I'm not too worried about it right now but thanks for calling it out.

**Comment by digitalghost-dev** [comment]
@JPHaus - sounds good, let's publish.
