### ISSUE TITLE
Feature: Project section?

### ISSUE THREAD

**Issue by digitalghost-dev** [data-engineering-community/data-engineering-wiki#40]
Hey, I've noticed that the subreddit for r/DataEngineering tends to have the same question over and over about projects and people asking for examples. How about adding a section in the wiki for people's open source data engineering projects?

**Comment by JPHaus** [comment]
Yeah, I like that idea. It would be nice if it were tagged and filterable but I don't think that's a hard requirement. We do have a link that comes up if you search project but it would be better if there were a standalone page. I've also tinkered around in the past with a little project idea generator app.

![image](https://github.com/data-engineering-community/data-engineering-wiki/assets/16173036/eb249829-625a-41b1-8a90-2c3aab35b567)

So I guess the easiest thing to do would be to have a table or use airtable for filtering functionality and just put it on a page (probably under community). I can make the page/add to airtable and if you're up for it I could use some help with sourcing which projects to display.

**Comment by digitalghost-dev** [comment]
Yeah, I can start sourcing some projects and make a list.

**Comment by digitalghost-dev** [comment]
@JPHaus - any sort of criteria you are looking for?

**Comment by digitalghost-dev** [comment]
Didn't seem to get any responses on the post. So, I was thinking that I can search for and get a list of 5 just to start.

**Comment by digitalghost-dev** [comment]
Okay, I think I have a starter list:
* **Community Source**: [NBA Data Modeling](https://github.com/jpooksy/NBA_Data_Modeling) - Parker Rogers
* **Community Source**: [stream-iot](https://github.com/fpgmaas/stream-iot) - Florian Maas
* **Community Source**: [Adidas-Sales](https://github.com/bfraz33/Adidas-Sales) - Brandon Frazier
* **Community Source**: [Reddit Sentiment Analysis Data Pipeline](https://github.com/nama1arpit/reddit-streaming-pipeline) - Arpit Nama
* **Community Source**:  [Premier League](https://github.com/digitalghost-dev/premier-league) - Christian Sanchez
* **Community Source**:  [Finnhub Streaming Data Pipeline](https://github.com/RSKriegs/finnhub-streaming-data-pipeline) - RSKriegs
* [Online Store](https://github.com/josephmachado/online_store) - Jospeh Machado
    * This project has [documentation](https://www.startdataengineering.com/post/data-engineering-project-e2e/) as well which I think adds more value.
 * [BitCoin Monitor](https://github.com/josephmachado/bitcoinMonitor) - Jospeh Machado
     * [Documentation](https://www.startdataengineering.com/post/data-engineering-project-to-impress-hiring-managers/)
