### ISSUE TITLE
Add spot instances to cost optimization guide

### ISSUE THREAD

**Issue by JPHaus** [data-engineering-community/data-engineering-wiki#47]
Under general compute there should be a section about using spot instances to save money if your workload can tolerate it.

https://github.com/data-engineering-community/data-engineering-wiki/blob/main/Guides/Cost%20Optimization%20in%20the%20Cloud.md

**Comment by lbg-oju** [comment]
Hi, can I be assigned this issue?

**Comment by JPHaus** [comment]
> Hi @JPHaus , can I be assigned this issue?

You got it boss
