### ISSUE TITLE
Side Pane Tool category not organized || Need more subfolders

### ISSUE THREAD

**Issue by Ravikumar10593-hub** [data-engineering-community/data-engineering-wiki#53]
When you expand the Tools sections on the sidebar you get options for `Data Ingestion` ....... `Workflow Orchestrators` and after that, all the tools are floating outside without any category:
![image](https://github.com/data-engineering-community/data-engineering-wiki/assets/65507584/85098c4b-3c53-48fd-bf53-fdc6aa1ef4fd)

Can't we add some more folders like the AWS Cloud tool with subfolders like storage and put `S3` inside that and the same case with all other tools?

Or to make it simple Put all AWS tools inside one AWS folder, all Azure-related stuff inside the Azure folder, and so on.

To recreate this issue:
- Go to https://dataengineering.wiki/Index and expand the Tools sidebar

OR 

- Click on this [link](https://dataengineering.wiki/Tools/Tools)

If possible you can assign me this task and I can help you guys to organize this.

**Comment by JPHaus** [comment]
We want to limit the number of nested folders as much as possible so I think folders by tool type instead of cloud/vendor would be better. With that in mind, what are some folders you think you would add?

**Comment by Ravikumar10593-hub** [comment]
Some of the categories I can think of on top of my mind is:

- Folder name `Data Acquisition`:
Items Inside this folder: Postman etc.. (we can add many more)

- Folder name `Data Processing`:
Items inside this folder: Apache Kafka (Not yet part of this documentation), Apache Spark, Hadoop MapReduce, etc..

- Folder name `Data Visualization & Analysis`:
Items inside this folder: Power BI, QlikView, QlikSense, Tableau, Looker 

- Folder name `AWS Specific Tool`:
Items inside this folder: All the AWS-specific tools

- Folder name `Azure Specific Tool`:
Items inside this folder: All the Azure-specific tools

- Folder name `GCP Specific Tool`:
Items inside this folder: All the GCP-specific tools

- Folder name `General Purpose tool`:
Items inside this folder: Python, R, Java, SQL, etc

This is something that I can think of, please let me know if this makes sense or we can have some more brainstorming.

Open to suggestions😊.

**Comment by Ravikumar10593-hub** [comment]
Should I go ahead and do it , or how do you want to go about this. Please let me know

**Comment by JPHaus** [comment]
We have to add aliases to all of the files moved so they redirect if someone goes to the old url. I can get to it later today but if you want to take a shot at it go for it.

**Comment by JPHaus** [comment]
I added some subfolders but haven't updated the links yet. I also did not make folders for the cloud provider notes because there are only 3 so I don't believe it needs a subfolder yet. Other things that aren't in subfolders yet are things related to metadata/metrics.

**Comment by Ravikumar10593-hub** [comment]
Oh cool, I see you have already created a PR for this, let me know if you need any help.

I am happy to help 😊
